// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZgNq45CpJkmYGQ_vaAhHmBb8MGk2GuL4',
    appId: '1:375038508299:web:ac3cfd9a78e736d729b60e',
    messagingSenderId: '375038508299',
    projectId: 'chat-app-tr-c199a',
    authDomain: 'chat-app-tr-c199a.firebaseapp.com',
    storageBucket: 'chat-app-tr-c199a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8CkPUgJxJeWjDp9-wFkViHviY_OLlZJA',
    appId: '1:375038508299:android:39901570ede65b1629b60e',
    messagingSenderId: '375038508299',
    projectId: 'chat-app-tr-c199a',
    storageBucket: 'chat-app-tr-c199a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd26T0GQYQ1FIH84hh0Y3xu7yt5TczYQM',
    appId: '1:375038508299:ios:403666c7cc58e0c129b60e',
    messagingSenderId: '375038508299',
    projectId: 'chat-app-tr-c199a',
    storageBucket: 'chat-app-tr-c199a.firebasestorage.app',
    iosBundleId: 'com.example.chatAppTr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd26T0GQYQ1FIH84hh0Y3xu7yt5TczYQM',
    appId: '1:375038508299:ios:403666c7cc58e0c129b60e',
    messagingSenderId: '375038508299',
    projectId: 'chat-app-tr-c199a',
    storageBucket: 'chat-app-tr-c199a.firebasestorage.app',
    iosBundleId: 'com.example.chatAppTr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZgNq45CpJkmYGQ_vaAhHmBb8MGk2GuL4',
    appId: '1:375038508299:web:16f8c61aa213c1e329b60e',
    messagingSenderId: '375038508299',
    projectId: 'chat-app-tr-c199a',
    authDomain: 'chat-app-tr-c199a.firebaseapp.com',
    storageBucket: 'chat-app-tr-c199a.firebasestorage.app',
  );
}
